name: Build solutions

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  buildlibp2p:
    name: Build Libp2p
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [release, debug]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
      - name: Build Libp2p.sln
        run: dotnet build src/dotnet-libp2p/libp2p/Libp2p.sln -c ${{ matrix.config }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: buildlibp2p
    strategy:
      matrix:
        config: [release, debug]
        solution: [Nethermind, EthereumTests, Benchmarks]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
      - name: Build ${{ matrix.solution }}.sln
        run: dotnet build src/Nethermind/${{ matrix.solution }}.sln -c ${{ matrix.config }}
