name: Publish packages

on:
  push:
    branches: [fix/ppa-copy-delay]

jobs:

  publish-ppa:
    name: Publish on PPA
    runs-on: ubuntu-latest
    steps:
      - name: Check out Nethermind repository
        uses: actions/checkout@v4
      - name: Set up GPG
        env:
          GPG_PASSPHRASE: ${{ secrets.PPA_GPG_PASSPHRASE }}
          GPG_SECRET_KEY: ${{ secrets.PPA_GPG_SECRET_KEY }}
        run: |
          echo $GPG_SECRET_KEY > SECRET_KEY
          echo $GPG_PASSPHRASE > $GITHUB_WORKSPACE/PASSPHRASE
          echo "Import GPG key"
          base64 --decode -i SECRET_KEY | gpg --import --no-tty --batch --yes
          echo "Import GPG owner trust"
          echo ${{ secrets.GPG_OWNERTRUST }} | base64 --decode | gpg --import-ownertrust
      - name: Install PPA dependencies
        run: sudo apt-get update && sudo apt-get install debhelper devscripts -y
      - name: Submit package
        env:
          PPA_GPG_KEYID: ${{ secrets.PPA_GPG_KEYID }}
          VERSION: 1.25.3
        working-directory: scripts/deployment
        run: |
          # This hack must be removed once we reach the v2
          echo $VERSION > ver
          fixed_version=$(awk -F. '{ print $1"."$2$3$4"0"}' ver)

          for release in "jammy" "focal" "mantic"
          do
            changelog="nethermind ($fixed_version) $release; urgency=high\n"
            changelog+="  * Nethermind v$VERSION\n"
            changelog+=" -- Nethermind <devops@nethermind.io>  $(date -R)"
            echo -e "$changelog" > debian/changelog
            debuild -S -uc -us
            cd ..
            debsign -p "gpg --batch --yes --no-tty --pinentry-mode loopback --passphrase-file $GITHUB_WORKSPACE/PASSPHRASE" -S -k$PPA_GPG_KEYID nethermind_${fixed_version}_source.changes
            #dput -f ppa:nethermindeth/nethermind nethermind_${fixed_version}_source.changes
            cd deployment
          done

